# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata: 
#   name: host-path-reclaim
# provisioner: docker.io/hostpath
# reclaimPolicy: Retain
# volumeBindingMode: WaitForFirstConsumer 

## --- # Azure based storage class 
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: test-jka
# parameters:
#   skuname: StandardSSD_LRS
# provisioner: disk.csi.azure.com
# reclaimPolicy: Retain
# volumeBindingMode: WaitForFirstConsumer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-with-pvc
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: myapp-with-pvc
  template:
    metadata:
      labels:
        app: myapp-with-pvc
    spec:
      securityContext: 
        fsGroup: 2000
        runAsGroup: 3000
        runAsUser: 1000
        runAsNonRoot: true
      containers:
        - name: myapp-with-pvc
          image: superzer0/debug-container:latest
          command: ["sh", "-c", "sleep 1h"]
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: shared-volume
              mountPath: /var/app/data
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: myapp-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp-pvc
spec:
  resources:
    requests:
      storage: 100M
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi # hostpath, azurefile-csi, managed-csi, test-jka
