apiVersion: apps/v1
kind: Deployment
metadata:
  name: sec-ctx-demo
spec:
  selector:
    matchLabels:
      app: sec-ctx-demo
  template:
    metadata:
      labels:
        app: sec-ctx-demo
    spec:
      securityContext:
        runAsUser: 1000 # set as a user to run all the processes in the container 
        runAsGroup: 3000 # must be specified otherwise root group will be used 
        fsGroup: 2000 # FSGroup is used to set the group that owns the pod volumes. 
        runAsNonRoot: true # kubernetes will not create the container when running user is root
        
      volumes: 
      - name: sec-ctx-vol
        emptyDir: {}
      containers:
      - name: sec-ctx-demo
        image: ngnix:1.28
        command: ["sh", "-c", "sleep 1h"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /data/demo
            name: sec-ctx-vol
        securityContext:
          allowPrivilegeEscalation: false

# some reading https://pet2cattle.com/2022/02/kubernetes-fsgroup 
# https://cloudogu.com/en/blog/k8s-app-ops-part-3-security-context-1#security-context
