apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: myapp
  replicas: 10
  template:
    metadata:
      labels:
        app: myapp
        version: 2.0.0
    spec:
      containers:
      - name: myapp
        image: nginx:stable-alpine3.17-slim
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
