apiVersion: apps/v1
kind: Deployment
metadata: 
  labels:
    app: myapp
  name: myap
spec:
  progressDeadlineSeconds: 60
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: myapp 
    spec:
      containers:
      - image: polarsquad/hello-world-app:master
        name: hello-world
        ports:
          - containerPort: 3000
        readinessProbe:
          httpGet:
            path : /
            {{- if .Values.failedDeployment }}
            port: 3001 # it is on purpose wrong so that deployment fails but containers are running 
            {{- else }}
            port: 3000 
            {{- end }}
