name: 🔒 mvc-app-build-tmpl.yaml

on:
  workflow_call:

jobs:
  build:
    permissions:
      contents:  read
    env:
      TEMPLATE-FILE: dotnet/mvc-app/infra/webapp.bicep
    name: Build for Deployment
    runs-on: ubuntu-latest
    steps:
    #checkout the repository
    - uses: actions/checkout@v4.2.1
      name: 'Checkout'
      with:
        show-progress: true
        fetch-depth: 1
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./dotnet/mvc-app
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./dotnet/mvc-app
    - name: Publish
      run: dotnet publish --output $GITHUB_WORKSPACE/app-publish --configuration Release --no-restore
      working-directory: ./dotnet/mvc-app
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-publish
        path: '${{ github.workspace}}/app-publish'
    - name: Upload bicep for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: bicep-template
        path: ${{ env.TEMPLATE-FILE }}

