# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build mvc-app
defaults:
  run:
    shell: bash

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Show directory tree
      run: tree
    - uses: actions/checkout@v4.2.1
      name: 'Checkout'
      with:
        show-progress: true
        fetch-depth: 1
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./dotnet/mvc-app
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./dotnet/mvc-app
    - name: Publish
      run: dotnet publish --output $GITHUB_WORKSPACE/app-publish --configuration Release --no-restore
      working-directory: ./dotnet/mvc-app
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-published
        path: '${{ github.workspace}}/app-publish'



